name: Fix RSS Crash (ViewModel Cache)

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [main, dev, master]
    paths:
      - '**/RssArticlesFragment.kt'
      - '**/RssArticlesViewModel.kt'

jobs:
  fix-crash:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Create Fix Patch
        run: |
          cat > fix-rss-crash.patch << 'EOF'
          diff --git a/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesViewModel.kt b/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesViewModel.kt
          index 123456..789abc 100644
          --- a/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesViewModel.kt
          +++ b/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesViewModel.kt
          @@ -1,6 +1,7 @@
           package io.legado.app.ui.rss.article
           
           import android.app.Application
          +import android.os.Bundle
           import androidx.lifecycle.viewModelScope
           import io.legado.app.base.BaseViewModel
           import io.legado.app.data.appDb
          @@ -15,6 +16,9 @@
               var sortName: String = ""
               var sortUrl: String = ""
               var searchKey: String? = null
          +    
          +    // 缓存最后一次加载的数据，用于Fragment重建时瞬间恢复
          +    var cachedArticles: List<RssArticle>? = null
               
               fun init(arguments: Bundle?) {
                   arguments?.let {
          diff --git a/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesFragment.kt b/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesFragment.kt
          index 123456..789abc 100644
          --- a/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesFragment.kt
          +++ b/app/src/main/java/io/legado/app/ui/rss/article/RssArticlesFragment.kt
          @@ -5,6 +5,7 @@ import android.graphics.Rect
           import android.os.Bundle
           import android.view.View
           import androidx.fragment.app.activityViewModels
          +import androidx.recyclerview.widget.RecyclerView
           import androidx.fragment.app.viewModels
           import androidx.lifecycle.Lifecycle
           import androidx.lifecycle.lifecycleScope
          @@ -40,15 +41,9 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
               private val binding by viewBinding(FragmentRssArticlesBinding::bind)
               private val activityViewModel by activityViewModels<RssSortViewModel>()
               override val viewModel by viewModels<RssArticlesViewModel>()
          -    private val isPreload by lazy { activityViewModel.rssSource?.preload ?: false }
          +    private val isPreload by lazy { activityViewModel.rssSource?.preload == true }
               private val orientation by lazy { resources.configuration.orientation }
          -    private val adapter: BaseRssArticlesAdapter<*> by lazy {
          -        when (activityViewModel.articleStyle) {
          -            1 -> RssArticlesAdapter1(requireContext(), this@RssArticlesFragment)
          -            2 -> RssArticlesAdapter2(requireContext(), this@RssArticlesFragment)
          -            4 -> RssArticlesAdapter4(requireContext(), this@RssArticlesFragment)
          -            3 -> RssArticlesAdapter3(requireContext(), this@RssArticlesFragment)
          -            else -> RssArticlesAdapter(requireContext(), this@RssArticlesFragment)
          -        }
          -    }
          +    
          +    // Adapter 改为可空变量，随 View 创建和销毁，防止 ViewHolder 状态污染
          +    private var adapter: BaseRssArticlesAdapter<*>? = null
               private val loadMoreView: LoadMoreView by lazy {
                   LoadMoreView(requireContext())
               }
          @@ -61,6 +56,9 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
               private var fullRefresh = true
               private var isFirstLoad = true
           
          +    // 新增：标记是否已从 ViewModel 缓存恢复，避免重复加载
          +    private var restoredFromCache = false
          +
               constructor(sortName: String, sortUrl: String, searchKey: String?) : this() {
                   arguments = Bundle().apply {
                       putString("sortName", sortName)
          @@ -72,8 +70,15 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
               override fun onFragmentCreated(view: View, savedInstanceState: Bundle?) {
                   viewModel.init(arguments)
                   initView()
          -        initData()
          +        
          +        // 优先从 ViewModel 缓存恢复数据（瞬间完成，无闪烁）
          +        viewModel.cachedArticles?.let { cachedList ->
          +            adapter?.setItems(cachedList)
          +            isFirstLoad = false
          +            restoredFromCache = true
          +        }
          +        
          +        initDataFlow()
               }
           
               private fun initView() = binding.run {
          @@ -111,7 +116,21 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
                           LinearLayoutManager(requireContext())
                       }
                   }
          +        
          +        // 关键修复：每次创建新的 Adapter 实例，避免复用导致状态混乱
          +        adapter = when (activityViewModel.articleStyle) {
          +            1 -> RssArticlesAdapter1(requireContext(), this@RssArticlesFragment)
          +            2 -> RssArticlesAdapter2(requireContext(), this@RssArticlesFragment)
          +            4 -> RssArticlesAdapter4(requireContext(), this@RssArticlesFragment)
          +            3 -> RssArticlesAdapter3(requireContext(), this@RssArticlesFragment)
          +            else -> RssArticlesAdapter(requireContext(), this@RssArticlesFragment)
          +        }
          +        
                   recyclerView.layoutManager = layoutManager
                   recyclerView.adapter = adapter
          +        
          +        // 关键修复：使用独立的 ViewHolder 缓存池，防止跨 Fragment 污染
          +        recyclerView.setRecycledViewPool(RecyclerView.RecycledViewPool())
          +        
                   adapter.addFooterView {
                       ViewLoadMoreBinding.bind(loadMoreView)
                   }
          @@ -138,7 +157,7 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
                   }
               }
           
          -    private fun initData() {
          +    private fun initDataFlow() {
                   val rssUrl = activityViewModel.url ?: return
                   articlesFlowJob?.cancel()
                   articlesFlowJob = viewLifecycleOwner.lifecycleScope.launch {
          @@ -146,7 +165,8 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
                           .catch {
                               AppLog.put("订阅文章界面获取数据失败\n${it.localizedMessage}", it)
                           }.flowOn(IO).collect { newList ->
          -                    if (fullRefresh || newList.isEmpty()) {
          +                    // 安全调用 adapter，防止在 Fragment 销毁后收到数据
          +                    if (fullRefresh || newList.isEmpty() || restoredFromCache) {
                               adapter.setItems(newList)
                           } else {
                               //用DiffUtil只对差异数据进行更新
          @@ -168,6 +188,8 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
                                   }
                               }, true)
                           }
          +                    // 更新 ViewModel 缓存
          +                    viewModel.cachedArticles = newList
                           delay(200) // 200毫秒防抖
                           isFirstLoad = false
                           restoredFromCache = false
          @@ -178,7 +200,7 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
               private fun loadArticles() {
                   fullRefresh = true
                   isFirstLoad = true
          -        restoredFromCache = false
          +        viewModel.cachedArticles = null // 强制刷新时清除缓存
                   activityViewModel.rssSource?.let {
                       viewModel.loadArticles(it)
                   }
          @@ -186,7 +208,7 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
           
               private fun scrollToBottom(forceLoad: Boolean = false) {
                   if (viewModel.isLoading) return
          -        fullRefresh = false
          +        fullRefresh = !forceLoad
                   if ((loadMoreView.hasMore && adapter.getActualItemCount() > 0) || forceLoad) {
                       loadMoreView.hasMore()
                       activityViewModel.rssSource?.let {
          @@ -197,7 +219,7 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
           
               override fun observeLiveBus() {
                   viewModel.loadErrorLiveData.observe(viewLifecycleOwner) {
          -            loadMoreView.error(it)
          +            loadMoreView?.error(it)
                   }
                   viewModel.loadFinallyLiveData.observe(viewLifecycleOwner) { hasMore ->
                       binding.refreshLayout.isRefreshing = false
          @@ -208,8 +230,21 @@ class RssArticlesFragment() : VMBaseFragment<RssArticlesViewModel>(R.layout.frag
               }
           
               override fun readRss(rssArticle: RssArticle) {
          -        fullRefresh = false //activityViewModel.read会触发数据库更新,此时进行差异化更新
          +        fullRefresh = false // activityViewModel.read会触发数据库更新,此时进行差异化更新
                   ReadRss.readRss(this, rssArticle, activityViewModel.rssSource)
               }
          +    
          +    // 关键修复：确保 Fragment View 销毁时清理资源，防止 RecyclerView 状态混乱
          +    override fun onDestroyView() {
          +        articlesFlowJob?.cancel()
          +        binding.recyclerView.stopScroll()
          +        binding.recyclerView.itemAnimator = null
          +        // 解绑 Adapter 防止 Glide 回调修改已销毁的 View
          +        binding.recyclerView.adapter = null
          +        adapter = null
          +        super.onDestroyView()
          +    }
           }
          EOF
      
      - name: Check if patch can be applied
        run: |
          if git apply --check fix-rss-crash.patch 2>/dev/null; then
            echo "PATCH_APPLICABLE=true" >> $GITHUB_ENV
          else
            echo "PATCH_APPLICABLE=false" >> $GITHUB_ENV
            echo "::warning::Patch cannot be applied automatically, manual fix required"
          fi
      
      - name: Apply Patch and Create PR
        if: env.PATCH_APPLICABLE == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 创建新分支
          git checkout -b fix/rss-crash-viewmodel-cache
          
          # 应用补丁
          git apply fix-rss-crash.patch
          
          # 提交
          git add .
          git commit -m "fix: RSS 列表崩溃 - ViewModel缓存 + Adapter随View生灭

          修复 IllegalArgumentException: Scrapped or attached views may not be recycled
          
          问题根源：
          - Adapter 使用 lazy 委托导致 Fragment View 重建时复用旧实例
          - StaggeredGridLayoutManager 与 Glide 异步回调在视图销毁时竞争
          - 缺少 onDestroyView 清理导致 ViewHolder 状态混乱
          
          修复方案：
          - Adapter 改为随 View 创建和销毁，彻底隔离状态
          - ViewModel 缓存数据实现瞬间恢复，无闪烁
          - 添加独立 RecycledViewPool 防止跨 Fragment 污染
          - 安全调用 adapter?.xxx 防止空指针
          
          兼容性：
          - 横竖屏切换自动保持数据
          - 快速切换标签页无崩溃"
          
          # 推送
          git push origin fix/rss-crash-viewmodel-cache
      
      - name: Create Pull Request
        if: env.PATCH_APPLICABLE == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix/rss-crash-viewmodel-cache
          title: 'Fix: RSS 列表崩溃 (Scrapped or attached views)'
          body: |
            ## 修复内容
            解决 `IllegalArgumentException: Scrapped or attached views may not be recycled` 崩溃
            
            ### 变更点
            - [x] 移除 Adapter lazy 初始化，改为随 View 创建
            - [x] ViewModel 增加数据缓存，实现瞬间恢复
            - [x] 添加 `onDestroyView` 彻底清理资源
            - [x] 使用独立 `RecycledViewPool` 隔离状态
            
            ### 测试建议
            1. 快速滑动 RSS 标签页
            2. 横竖屏切换
            3. 下拉刷新时快速切换标签
            4. 后台长时间停留后恢复
            
            关联 Issue: 阅读崩溃报错日志
            
          draft: false
